language:
- python
python:
- '3.4'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: e+qtzqouO3+Fs6m5tZ/j/flz/6hukiYFzHjHZbqdmYsX7qHYjdEOT7k1WwgzGxSpqok87C/mCNwYS6aS7aOgaCD0sFh89+AH+sDRXNAV1MFPj64mXttjbHrpfk0DXkdPNUFZzLUk6IGV7SsK7l1cZEJVaIIiVq3u0I/7K6I2KJ1UwMOuh52qTPc1GqIDqmMG8zpgMkATgkCfHhPSVC9s9QYZIj4P6xCAkPgRuTu4UuTGF8Sf7qUSwiZwMlziaAh2tgAZT+jYXvuo01LeTZ0ot2gngynBPsrTtuklGH9+L82YO5rxpPhJ6e59ldDM7HvtN3NRvS76xUwFcZgLMy7hG+xN2qxpUf19zLdBMIy1KV8GbkupwRPomf4TMEfNuw6PQcBQjLQwRCtZEmczyMLwnVhVoxn7j4dsM7BxhwGPyF2y0jAlAfNE543Z2YMIntuQ0LYZGD724vbWUaXHivVy9SX4t28BHtGlOj0kBtwB5RCflMbLshvjlXX7N+ujycQnk2R8XxLkn6met4gA8oDdLysfGsW0PsW5VRBZKnMEvGC8/gaukkUQO2PQZvrYs1+Y3pIDRo3IxPdVwz97UL0XVlrf+XLnmL+5GuRll1De1+9/M87qvVbZw5T5K6/QhG9bbeNYuLNf2drrJihWIQ9m/jQCC3TY7yJYXXGEna4wYHY=
  app: tamara-stocks
  on:
    branch: master
    repo: kurtgn/tamara-stocks
